name: Snyk Library Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  snyk-library-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # THIS ACTION EXISTS
      - name: Install Snyk CLI
        uses: snyk/actions/setup@v3

      - name: Run Snyk SCA Scan
        env:
          SNYK_TOKEN: c80a2012-bb87-4482-beb5-399c664f183d
        run: |
          snyk test --all-projects || true

      - name: Generate SARIF
        env:
          SNYK_TOKEN: c80a2012-bb87-4482-beb5-399c664f183d
        run: |
          snyk test --all-projects --sarif-file-output=snyk.sarif || true

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
